name: DodoNest
options:
  bundleIdPrefix: com.dodonest
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
  configs:
    Release:
      # For unsigned distribution (remove these when you have a Developer ID)
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO

targets:
  DodoNest:
    type: application
    platform: macOS
    sources:
      - path: DodoNest
        excludes:
          - "**/Info.plist"
          - "DodoNest/Resources/Assets.xcassets"
      - path: DodoNest/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dodonest.app
        INFOPLIST_FILE: DodoNest/Resources/Info.plist
        PRODUCT_NAME: DodoNest
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_ENTITLEMENTS: DodoNest/Resources/DodoNest.entitlements
    entitlements:
      path: DodoNest/Resources/DodoNest.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.automation.apple-events: true

schemes:
  DodoNest:
    build:
      targets:
        DodoNest: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
